{
 "title": "Istio Control Plane Dashboard",
 "tags": [
  "istio",
  "control-plane"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Control Plane Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"pilot\"}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total)"
    }
   ]
  },
  {
   "title": "Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(rate(istio_requests_total{response_code=~\"5.*\"}[5m])) / sum(rate(istio_requests_total[5m])))"
    }
   ]
  },
  {
   "title": "Global Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  }
 ]
}